version: "3"
services:

  mysql_container:
    image: mysql:latest
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=publication
    volumes:
      - ./mysql-db:/var/lib/mysql

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-db:/data/db



